package:
  name: prsedm
  version: "1.0.3"

source:
  url: https://pypi.io/packages/source/p/prsedm/prsedm-1.0.3.tar.gz

build:
  number: 0
  # noarch removed – pysam has C-extensions
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -v"

requirements:
  host:
    - python >=3.9
    - numpy >=1.21,<2.0
    - pip

  run:
    - python >=3.10
    - numpy >=1.21,<2.0
    - joblib >=1.3
    - pandas >=2.2
    - pysam >=0.23.3
    - openssl >=3.0,<4.0

test:
  imports:
    - prsedm
    - prsedm.extensions.score_dm
  commands:
    - prsedm --help

about:
  home: https://github.com/sethsh7/PRSedm
  license: MIT
  license_family: MIT
  summary: >
    PRSedm (Polygenic Risk Score Extension for Diabetes Mellitus) is a package
    for local and remote generation of Polygenic Risk Scores (PRS) for Diabetes Mellitus (DM).
  description: |
    PRSedm is a Python package designed to calculate Polygenic Risk Scores (PRS)
    specifically tailored for Diabetes Mellitus (DM). It supports both local computation
    and remote workflows, ensuring flexibility and ease of use.
  dev_url: https://github.com/sethsh7/PRSedm
  doc_url: https://github.com/sethsh7/PRSedm#usage

extra:
  recipe-maintainers:
    - sethsh7
  channels:
    - bioconda
    - conda-forge  # main dependency channel